### ISSUE TITLE
深色模式显示有问题

### ISSUE THREAD

**Issue by grisbear** [ssjy1919/Obsidian-minitabs#1]
![2023-11-25_093600](https://github.com/ssjy1919/Obsidian-minitabs/assets/74553083/646b8136-3d29-42f5-abef-fe6887791860)

**Comment by ssjy1919** [comment]
> ![2023-11-25_093600](https://private-user-images.githubusercontent.com/74553083/285559164-646b8136-3d29-42f5-abef-fe6887791860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4ODA3MDQsIm5iZiI6MTcwMDg4MDQwNCwicGF0aCI6Ii83NDU1MzA4My8yODU1NTkxNjQtNjQ2YjgxMzYtM2QyOS00MmY1LWFiZWYtZmU2ODg3NzkxODYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDAyNDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNjRiNGUxNmMyYzAyMjQwMWI1NWUzMWU2NWRiNzczNWE2MDMzMDZiMDdlMTkwNDkzZGIwMWU5NTUzZWM0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wj--Smv2TSGWv1x5tD--TiLbuLDCIG7hmxZjqPCYqI8)

Now the dark theme color has been processed
