### ISSUE TITLE
四象限在预览或阅读视图下，点击完成任务后，并不会改变源码

### ISSUE THREAD

**Issue by fatsen** [ssjy1919/Obsidian-minitabs#2]
如下图所示。问下能否解决（不一定是bug，印象中dataview也是同样的行为）。谢谢

![image](https://github.com/ssjy1919/Obsidian-minitabs/assets/29320614/97f2e74d-ce62-4c9d-9721-41f5ed1ea302)

![image](https://github.com/ssjy1919/Obsidian-minitabs/assets/29320614/5e20e428-9d4c-4e9c-bfcb-80fab5b21b48)

**Comment by ssjy1919** [comment]
> 如下图所示。问下能否解决（不一定是bug，印象中dataview也是同样的行为）。谢谢
> 
> ![image](https://private-user-images.githubusercontent.com/29320614/287618559-97f2e74d-ce62-4c9d-9721-41f5ed1ea302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODU4NDQsIm5iZiI6MTcwMTY4NTU0NCwicGF0aCI6Ii8yOTMyMDYxNC8yODc2MTg1NTktOTdmMmU3NGQtY2U2Mi00YzlkLTk3MjEtNDFmNWVkMWVhMzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEwMjU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMmI5YmRlMjYwOTc4NzVlZGM3OTJmOGJhNTNjYjZiY2EzNjY5NzQ5ZjFmNDM0YmVjMGRmZTBkNTdjNzNhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lAHsMEyCeBSH1nnzZEOk57L0TXvwdaF24eLdIN2RYmw)
> 
> ![image](https://private-user-images.githubusercontent.com/29320614/287618745-5e20e428-9d4c-4e9c-bfcb-80fab5b21b48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODU4NDQsIm5iZiI6MTcwMTY4NTU0NCwicGF0aCI6Ii8yOTMyMDYxNC8yODc2MTg3NDUtNWUyMGU0MjgtOWQ0Yy00ZTljLWJmY2ItODBmYWI1YjIxYjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEwMjU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzY0MjQzNzM1NTU3NWE0N2FmNjhkYTQ2MGUzYWY2NzVmMGUxNDU4ZGVjOTRhYTE3ZmIwNDFhMjUzMGNkYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JXgkkfhAO-xO2XAIMAj9LtEMgAJg2xnFKFoA5or9tm8)

你是对的。
我推荐把任务写在其他文件（比如日记），然后通过dataview插件或者tasks插件聚集到四象限视图里面查看。这样是可以正常使用的。
您可以告诉我，有什么应用场景需要直接把任务写到四象限视图里面吗？谢谢

**Comment by fatsen** [comment]
> > 如下图所示。问下能否解决（不一定是bug，印象中dataview也是同样的行为）。谢谢
> > ![image](https://private-user-images.githubusercontent.com/29320614/287618559-97f2e74d-ce62-4c9d-9721-41f5ed1ea302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODU4NDQsIm5iZiI6MTcwMTY4NTU0NCwicGF0aCI6Ii8yOTMyMDYxNC8yODc2MTg1NTktOTdmMmU3NGQtY2U2Mi00YzlkLTk3MjEtNDFmNWVkMWVhMzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEwMjU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMmI5YmRlMjYwOTc4NzVlZGM3OTJmOGJhNTNjYjZiY2EzNjY5NzQ5ZjFmNDM0YmVjMGRmZTBkNTdjNzNhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lAHsMEyCeBSH1nnzZEOk57L0TXvwdaF24eLdIN2RYmw)
> > ![image](https://private-user-images.githubusercontent.com/29320614/287618745-5e20e428-9d4c-4e9c-bfcb-80fab5b21b48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODU4NDQsIm5iZiI6MTcwMTY4NTU0NCwicGF0aCI6Ii8yOTMyMDYxNC8yODc2MTg3NDUtNWUyMGU0MjgtOWQ0Yy00ZTljLWJmY2ItODBmYWI1YjIxYjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEwMjU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzY0MjQzNzM1NTU3NWE0N2FmNjhkYTQ2MGUzYWY2NzVmMGUxNDU4ZGVjOTRhYTE3ZmIwNDFhMjUzMGNkYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JXgkkfhAO-xO2XAIMAj9LtEMgAJg2xnFKFoA5or9tm8)
> 
> 你是对的。 我推荐把任务写在其他文件（比如日记），然后通过dataview插件或者tasks插件聚集到四象限视图里面查看。这样是可以正常使用的。 您可以告诉我，有什么应用场景需要直接把任务写到四象限视图里面吗？谢谢

我的应用场景实际上是任务完成时，希望能够在视图里面直接点击，直接完成任务（现在我也是写在其他文件中的）。我现在是在dataview视图中点开任务所在的文件，然后完成任务；能正常使用，也没有多麻烦，只是感觉不流畅，其实也能接受。
谢谢回复！（上github的频率较低，刚看到）
